### ISSUE TITLE
有个小问题

### ISSUE THREAD

**Issue by Faceisme** [Eronana/scimex#2]
大佬,您好,很荣幸在GIthub上看到您的项目,
 
我是做其他开发的码农一枚,因为喜欢原生输入法,但是又一直被 "中文无法输入英文符号" 困扰,写代码很不方便,很庆幸遇到您的项目

我有用 Karabiner-Elements  做键盘映射, caps 映射为shift, 因为shift 不能精确的 100%成功切换输入法, 

所以,冒昧的像你请教一下,如何取消您代码里的 "shift切换中英文" 这个功能 ? 

希望您百忙中能帮小弟解答一下困惑,谢谢🙏!!

**Comment by Eronana** [comment]
干掉和shift有关的代码就行
文件: `src/injlib/injlib.m`
![image](https://user-images.githubusercontent.com/9164153/60171899-20f78f00-983e-11e9-877c-fb3d8e928418.png)

**Comment by Eronana** [comment]
不过现在并不建议使用了, 因为并不支持`Mojave`.
我也懒得修了, 已经转搜狗了.

**Comment by Faceisme** [comment]
非常感谢大佬的回答,但是....我是10.14.5的系统,完美使用,大佬您也试试看哦
