### ISSUE TITLE
考虑支持一下 big sur 吗？

### ISSUE THREAD

**Issue by YunshuaiPeng** [Eronana/scimex#3]

**Comment by Eronana** [comment]
呃 我换搜狗了(手动doge

**Comment by impys** [comment]
> 呃 我换搜狗了(手动doge

**Comment by YunshuaiPeng** [comment]
那我也换搜狗 doge

**Comment by Eronana** [comment]
现在支持Big Sur了.
其实也没改动什么, 一是修复了一处编译错误, 二是macOS要完全禁用SIP(Big Sur似乎不支持enable --without debug了)
很惭愧 做了两点微小的工作

**Comment by YunshuaiPeng** [comment]
@Eronana  Amazing, 已经用上了, 然后立刻马上卸载了搜狗. 非常感谢大佬的付出.
